export class Cadastro {
  constructor(
    public id?: number,
    public tipo_proponente?: string,
    public nome_responsavel?: string,
    public cpf?: string,
    public telefone?: string,
    public email?: string,
    public cnpj?: string,
    public password?: string,
    public confirm_password?: string,
    public nome_empreendimento?: string,
    public profile_id?: number,
    public cep?: string,
    public cidade?: number,
    public bairro?: string,
    public rua?: string,
    public numero?: string,
    public complemento?: string,
    public iniciativa_impacto?: string,
    public cadastro_cadimpacto?: string,
    public status_atual?: string,
    public area_atuacao?: string,
    public resumo_negocio?: string,
    public rg?: string,
    public cartaoCnpj?: string,
    public fotos?: string,
    public aceite_termos?: boolean,
    public linha_credito?: string,
  ){}
}
